version: "3.3"

services:

  time:
    image: yiisoftware/yii2-php:8.0-apache
    container_name: time_c
    ports:
      - 9001:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.time.rule=Host(`time.localhost`)"
      - "traefik.http.routers.time.entrypoints=web"
    networks:
      - lily2
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated

networks:
  lily2:
    external:
      name: lily_network

volumes:
  app:


